# Generated by Django 4.2 on 2023-04-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_collection', '0002_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=43, unique=True),
        ),
    ]
